### ISSUE TITLE
ER diagram

### ISSUE THREAD

**Issue by jernejbanevec** [jonagricar/eMuzej#1]
Pozdrav!
Pregledal sem ER diagram in imam naslednje pripombe:
* entiteta _MERE_ tu najbrž ni potrebna, saj se lahko višino in širino umetnine dopiše kar kot argument entitete _UMETNINA_,
* za primaren ključ entitete _UMETNIK_ priporočam kar _id_, saj sta se mogoče dva umetnika enako imenovala (morda bi se nov _id_ uporabilo tudi za primaren ključ entitete _OBDOBJE_),
* kot argument entitete _UMETNINA_ je podan tudi avtor (se ta morda razlikuje od umetnika, ki je umetnino ustvaril?),
* vsak umetnik pa je najbrž deloval v vsaj enem obdobju (uporaba odebeljene črte).

**Comment by jonagricar** [comment]
Najlepša hvala za komentar! Sva uredili.
